#pragma once

#define FPS 60
#define SCREEN_HEIGHT 400
#define SCREEN_WIDTH 1200

#define PLAYER_WIDTH 20
#define PLAYER_HEIGHT 30
#define PLAYER_JUMP_V -20.0f
#define PLAYER_JUMP_SMALL_V -8.0f
#define PLAYER_HORIZONTAL_SPEED 2.0f
#define PLAYER_HORIZONTAL_SPEED_FAST 12.0f
#define PLAYER_GRAVITY_SLOWDOWN 0.87f
#define PLAYER_GRAVITY_ACCELERATE 1.1f
#define PLAYER_GRAVITY_BACKFALL_TRESHOLD 1.0f
#define PLAYER_GRAVITY_MAX_ACCELERATE 8.0f
#define PLAYER_LIFT_FROM_BELOW_TRESHOLD -15.0f
#define PLAYER_ON_GROUND_TRESHOLD 5.0f

#define FRICTION_ZERO_TRESHOLD 1.0f

#define GROUND_AWARENESS_LIFT_THRESHOLD 6.0f
